# Generated by Django 3.0.2 on 2023-12-19 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20231128_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='year',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
