# Generated by Django 3.0.2 on 2024-10-23 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='crossword_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('mcq', 'Multiple Choice'), ('crossword', 'Crossword')], max_length=10),
        ),
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.TextField()),
                ('across_clues', models.TextField()),
                ('down_clues', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crossword', to='quiz.Question')),
            ],
        ),
    ]
