# Generated by Django 3.0.2 on 2024-10-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20241023_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_choices',
            field=models.ManyToManyField(blank=True, related_name='correct_for_questions', to='quiz.Choice'),
        ),
        migrations.DeleteModel(
            name='Crossword',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
