# Generated by Django 3.0.2 on 2024-10-23 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_auto_20241023_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_choices',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('text', 'Short Text'), ('crossword', 'Crossword')], max_length=10),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
