# Generated by Django 3.0.2 on 2024-10-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20241023_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.TextField()),
                ('across_clues', models.TextField()),
                ('down_clues', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='points',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('mcq', 'Multiple Choice'), ('crossword', 'Crossword')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.AddField(
            model_name='crossword',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crossword', to='quiz.Question'),
        ),
    ]
